import Slash from './Slash';

const registry = {
  // Legacy/explicit keys still referenced in code
  fireball: Slash,
  fireballP1: Slash,
  fireballP2: Slash,
  blaze: Slash,
  slash: Slash,
  javelin: Slash,
  pierce: Slash,

  // Sprite sheet animation keys (all map to Slash component which handles sprite sheets)
  'Acid Pool_2x2_4frames': Slash,
  'Acid_2x2_4frames': Slash,
  'Affliction_2x2_4frames': Slash,
  'Arcane Blast_2x2_4frames': Slash,
  'Arcane Bolt_2x2_4frames': Slash,
  'Arcane Explosion_2x2_4frames': Slash,
  'Arcane Explosion Secondary_2x2_4frames': Slash,
  'Arrest_2x2_4frames': Slash,
  'Arrow_2x2_4frames': Slash,
  'Armor Break_2x2_4frames': Slash,
  'Armor Melt_2x2_4frames': Slash,
  'Assassinate_2x2_4frames': Slash,
  'Avalanche_2x2_4frames': Slash,
  'Barrel Smash_2x2_4frames': Slash,
  'Battle Formation_2x2_4frames': Slash,
  'Basic Attack_2x2_4frames': Slash,
  'Bat Swarm_2x2_4frames': Slash,
  'Bear Swipe_2x2_4frames': Slash,
  'Bite_2x2_4frames': Slash,
  'Berserk_2x2_4frames': Slash,
  'Black Arrow_2x2_4frames': Slash,
  'Benevolence_2x2_4frames': Slash,
  'Blaze_2x2_4frames': Slash,
  'Blizzard_2x2_4frames': Slash,
  'Blow Dart_2x2_4frames': Slash,
  'Blood Drain_2x2_4frames': Slash,
  'Blood Lust_2x2_4frames': Slash,
  'Bloody Fangs_2x2_4frames': Slash,
  'Ghost Ghostly Attack_2x2_4frames': Slash,
  'Ghost Ultimate Devistation_2x2_4frames': Slash,
  'Ghost Ultimate Devastation_2x2_4frames': Slash,
  'Ghost Whirlwind Primary_2x2_4frames': Slash,
  'Ghost Whirlwind Secondary_2x2_4frames': Slash,
  'Body Slam_2x2_4frames': Slash,
  'Brutal Smash_2x2_4frames': Slash,
  'Monstrous Claws_2x2_4frames': Slash,
  'Bomb Toss_2x2_4frames': Slash,
  'Bomb Toss Secondary_2x2_4frames': Slash,
  'Boulder_2x2_4frames': Slash,
  'Brimberry Leaves_2x2_4frames': Slash,
  'Charge_2x2_4frames': Slash,
  'Club Smash_2x2_4frames': Slash,
  'Claw_2x2_4frames': Slash,
  'Cleanse_2x2_4frames': Slash,
  'Cone Of Cold_2x2_4frames': Slash,
  'Conflagration_2x2_4frames': Slash,
  'Coup_2x2_4frames': Slash,
  'Consume Burn_2x2_4frames': Slash,
  'Consumed By Flames_2x2_4frames': Slash,
  'Cleansing Water_2x2_4frames': Slash,
  'Corpse Explosion_2x2_4frames': Slash,
  'Counter_2x2_4frames': Slash,
  'Corrupting Tongue_2x2_4frames': Slash,
  'Curse_2x2_4frames': Slash,
  'Cut_2x2_4frames': Slash,
  'Dark Bolt_2x2_4frames': Slash,
  'Dark Energy_2x2_4frames': Slash,
  'Boss Double Strike_2x2_4frames': Slash,
  'Boss Tremor_2x2_4frames': Slash,
  'Boss Dark Energy_2x2_4frames': Slash,
  'Dark Pillar_2x2_4frames': Slash,
  'Dark Slash_2x2_4frames': Slash,
  'Duel_2x2_4frames': Slash,
  'Duality Strike_2x2_4frames': Slash,
  'Dead Eye_2x2_4frames': Slash,
  'Deadly Fist_2x2_4frames': Slash,
  'Death Pact_2x2_4frames': Slash,
  'Decree Of Hatred_2x2_4frames': Slash,
  'Dragon Bite_2x2_4frames': Slash,
  'Dragon Breath_2x2_4frames': Slash,
  'Dragon Fangs_2x2_4frames': Slash,
  'Dragons Claw_2x2_4frames': Slash,
  'Drain_2x2_4frames': Slash,
  'Elixir_2x2_4frames': Slash,
  'Energy Wave_2x2_4frames': Slash,
  'Energy Blast_2x2_4frames': Slash,
  'Engage_2x2_4frames': Slash,
  'Entangling Roots_2x2_4frames': Slash,
  'Experimental Toxin_2x2_4frames': Slash,
  'Excecute_2x2_4frames': Slash,
  'Excorcism_2x2_4frames': Slash,
  'Fan_2x2_4frames': Slash,
  'Fire Bolt_2x2_4frames': Slash,
  'Fire Bomb_2x2_4frames': Slash,
  'Fire Bomb Secondary_2x2_4frames': Slash,
  'Fire Breath_2x2_4frames': Slash,
  'Flex_2x2_4frames': Slash,
  'Flame Thrower_2x2_4frames': Slash,
  'Flank_2x2_4frames': Slash,
  'Forked Lightning_2x2_4frames': Slash,
  'Gale_2x2_4frames': Slash,
  'Gravity_2x2_4frames': Slash,
  'Guillotine_2x2_4frames': Slash,
  'Hammer_2x2_4frames': Slash,
  'Hex_2x2_4frames': Slash,
  'Justice_2x2_4frames': Slash,
  'Hamstring_2x2_4frames': Slash,
  'Harakiri_2x2_4frames': Slash,
  'Healing_2x2_4frames': Slash,
  'Healing Water_2x2_4frames': Slash,
  'Herbs_2x2_4frames': Slash,
  'Honor_2x2_4frames': Slash,
  'Howl_2x2_4frames': Slash,
  'Humiliation_2x2_4frames': Slash,
  'Humble_2x2_4frames': Slash,
  'Ice Bolt_2x2_4frames': Slash,
  'Iron Forge_2x2_4frames': Slash,
  'Iron Hand_2x2_4frames': Slash,
  'Javelin_2x2_4frames': Slash,
  'Leech_2x2_4frames': Slash,
  'Landmine Placement_2x2_4frames': Slash,
  'Landmine Explosions_2x2_4frames': Slash,
  'Life for a Life_2x2_4frames': Slash,
  'Light Pillar_2x2_4frames': Slash,
  'Lightning Bolt_2x2_4frames': Slash,
  'Magnetize_2x2_4frames': Slash,
  'Malign_2x2_4frames': Slash,
  'Maul_2x2_4frames': Slash,
  'Minion_2x2_4frames': Slash,
  'Masamune_2x2_4frames': Slash,
  'Meteor_2x2_4frames': Slash,
  'Molten Pour_2x2_4frames': Slash,
  'Multi Shot_2x2_4frames': Slash,
  'Mud Armor_2x2_4frames': Slash,
  'Mud Sling_2x2_4frames': Slash,
  'Quicksand_2x2_4frames': Slash,
  'Raise Dead_2x2_4frames': Slash,
  'Reclaim Throne_2x2_4frames': Slash,
  'Natures Blessing_2x2_4frames': Slash,
  'Oops_2x2_4frames': Slash,
  'Oops Secondary_2x2_4frames': Slash,
  'Pierce_2x2_4frames': Slash,
  'Pilfer_2x2_4frames': Slash,
  'Poison Breath_2x2_4frames': Slash,
  'Poison Dagger_2x2_4frames': Slash,
  'Poison Explosion_2x2_4frames': Slash,
  'Poison Hairpin_2c2_4frames': Slash,
  'Poison_2x2_4frames': Slash,
  'Prayer_2x2_4frames': Slash,
  'Priority Target_2x2_4frames': Slash,
  'Purify_2x2_4frames': Slash,
  "Queen's Wrath_2x2_4frames": Slash,
  'Scythes Harvest_2x2_4frames': Slash,
  'Cleave_2x2_4frames': Slash,
  'Combo_2x2_4frames': Slash,
  'Combo Secondary_2x2_4frames': Slash,
  'Rage_2x2_4frames': Slash,
  'Ritual_2x2_4frames': Slash,
  'Release The Inmates_2x2_4frames': Slash,
  'Venom Strike_2x2_4frames': Slash,
  'Revive_2x2_4frames': Slash,
  'Rock Smash_2x2_4frames': Slash,
  'Searing Light_2x2_4frames': Slash,
  'Chain Whipe_2x2_4frames': Slash,
  'Siphon_2x2_4frames': Slash,
  'Shackle_2x2_4frames': Slash,
  'Shadow Strike_2x2_4frames': Slash,
  'Shuriken_2x2_4frames': Slash,
  'Shield Bash_2x2_4frames': Slash,
  'Skirmish_2x2_4frames': Slash,
  'Spores_2x2_4frames': Slash,
  'Natures Wrath_2x2_4frames': Slash,
  'Fruit Of The Vine_2x2_4frames': Slash,
  'Slap_2x2_4frames': Slash,
  'Slash_2x2_4frames': Slash,
  'Smoke Bomb_2x2_4frames': Slash,
  'Sneak attack_2x2_4frames': Slash,
  'Soul Crush_2x2_4frames': Slash,
  'Soul Drain_2x2_4frames': Slash,
  'Spook_2x2_4frames': Slash,
  'Spear_2x2_4frames': Slash,
  'Special Brew_2x2_4frames': Slash,
  'Stab_2x2_4frames': Slash,
  'Stomp_2x2_4frames': Slash,
  'Summon Ally_2x2_4frames': Slash,
  'Tail Whip_2x2_4frames': Slash,
  'Table Tilt_2x2_4frames': Slash,
  'Turret_2x2_4frames': Slash,
  'Throw Boulder_2x2_4frames': Slash,
  'Track Down_2x2_4frames': Slash,
  'Time Warp_2x2_4frames': Slash,
  'Treachery_2x2_4frames': Slash,
  'Tyranny_2x2_4frames': Slash,
  'Truth_2x2_4frames': Slash,
  'Trample_2x2_4frames': Slash,
  'Throw Rock_2x2_4frames': Slash,
  'Tidal Wave_2x2_4frames': Slash,
  'Toads_2x2_4frames': Slash,
  'Toads Secondary_2x2_4frames': Slash,
  'Vengeful Slash_2x2_4frames': Slash,
  'Vicious Bite_2x2_4frames': Slash,
  'Vortex_2x2_4frames': Slash,
  'Wild Punch_2x2_4frames': Slash,
  'Wild Fire_2x2_4frames': Slash,
  'Wolf Claw_2x2_4frames': Slash,
  "Zeus's Wrath_2x2_4frames": Slash,
  'Chop_2x2_4frames': Slash,
  'Axe Throw_2x2_4frames': Slash,
  'Battle Projectile_2x2_4frames': Slash,
  'Force Blast_2x2_4frames': Slash,
  'Staff Finisher_2x2_4frames': Slash,
  'Superiority_2x2_4frames': Slash,
  'Swiftness_2x2_4frames': Slash,
  'Usurrp_2x2_4frames': Slash,
};

export default registry;
export const getAnimation = (name) => registry[name];
