import Slash from './Slash';

const registry = {
  // Legacy/explicit keys still referenced in code
  fireball: Slash,
  fireballP1: Slash,
  fireballP2: Slash,
  blaze: Slash,
  slash: Slash,
  javelin: Slash,
  pierce: Slash,

  // Sprite sheet animation keys (all map to Slash component which handles sprite sheets)
  'Acid Pool_2x2_4frames': Slash,
  'Acid_2x2_4frames': Slash,
  'Arcane Blast_2x2_4frames': Slash,
  'Arcane Bolt_2x2_4frames': Slash,
  'Arcane Explosion_2x2_4frames': Slash,
  'Arcane Explosion Secondary_2x2_4frames': Slash,
  'Arrest_2x2_4frames': Slash,
  'Arrow_2x2_4frames': Slash,
  'Armor Melt_2x2_4frames': Slash,
  'Assassinate_2x2_4frames': Slash,
  'Barrel Smash_2x2_4frames': Slash,
  'Bear Swipe_2x2_4frames': Slash,
  'Berserk_2x2_4frames': Slash,
  'Blaze_2x2_4frames': Slash,
  'Blizzard_2x2_4frames': Slash,
  'Blow Dart_2x2_4frames': Slash,
  'Blood Drain_2x2_4frames': Slash,
  'Brutal Smash_2x2_4frames': Slash,
  'Monstrous Claws_2x2_4frames': Slash,
  'Bomb Toss_2x2_4frames': Slash,
  'Bomb Toss Secondary_2x2_4frames': Slash,
  'Boulder_2x2_4frames': Slash,
  'Brimberry Leaves_2x2_4frames': Slash,
  'Charge_2x2_4frames': Slash,
  'Claw_2x2_4frames': Slash,
  'Cleanse_2x2_4frames': Slash,
  'Cone Of Cold_2x2_4frames': Slash,
  'Consume Burn_2x2_4frames': Slash,
  'Consumed By Flames_2x2_4frames': Slash,
  'Counter_2x2_4frames': Slash,
  'Curse_2x2_4frames': Slash,
  'Cut_2x2_4frames': Slash,
  'Dark Bolt_2x2_4frames': Slash,
  'Dark Pillar_2x2_4frames': Slash,
  'Dark Slash_2x2_4frames': Slash,
  'Dead Eye_2x2_4frames': Slash,
  'Death Pact_2x2_4frames': Slash,
  'Dragon Bite_2x2_4frames': Slash,
  'Dragon Breath_2x2_4frames': Slash,
  'Dragon Fangs_2x2_4frames': Slash,
  'Dragons Claw_2x2_4frames': Slash,
  'Drain_2x2_4frames': Slash,
  'Elixir_2x2_4frames': Slash,
  'Experimental Toxin_2x2_4frames': Slash,
  'Excecute_2x2_4frames': Slash,
  'Fan_2x2_4frames': Slash,
  'Fire Bolt_2x2_4frames': Slash,
  'Fire Bomb_2x2_4frames': Slash,
  'Fire Bomb Secondary_2x2_4frames': Slash,
  'Fire Breath_2x2_4frames': Slash,
  'Forked Lightning_2x2_4frames': Slash,
  'Gale_2x2_4frames': Slash,
  'Gravity_2x2_4frames': Slash,
  'Guillotine': Slash,
  'Hammer_2x2_4frames': Slash,
  'Hamstring_2x2_4frames': Slash,
  'Healing_2x2_4frames': Slash,
  'Humiliation_2x2_4frames': Slash,
  'Ice Bolt_2x2_4frames': Slash,
  'Iron Forge_2x2_4frames': Slash,
  'Javelin_2x2_4frames': Slash,
  'Leech_2x2_4frames': Slash,
  'Light Pillar_2x2_4frames': Slash,
  'Lightning Bolt_2x2_4frames': Slash,
  'Malign_2x2_4frames': Slash,
  'Meteor_2x2_4frames': Slash,
  'Molten Pour_2x2_4frames': Slash,
  'Multi Shot_2x2_4frames': Slash,
  'Oops_2x2_4frames': Slash,
  'Oops Secondary_2x2_4frames': Slash,
  'Pierce_2x2_4frames': Slash,
  'Poison Breath_2x2_4frames': Slash,
  'Poison Dagger_2x2_4frames': Slash,
  'Poison Hairpin_2c2_4frames': Slash,
  'Prayer_2x2_4frames': Slash,
  'Priority Target_2x2_4frames': Slash,
  'Purify_2x2_4frames': Slash,
  'Rage_2x2_4frames': Slash,
  'Siphon_2x2_4frames': Slash,
  'Shackle_2x2_4frames': Slash,
  'Slap_2x2_4frames': Slash,
  'Slash_2x2_4frames': Slash,
  'Sneak attack_2x2_4frames': Slash,
  'Soul Crush_2x2_4frames': Slash,
  'Spear_2x2_4frames': Slash,
  'Special Brew_2x2_4frames': Slash,
  'Tail Whip_2x2_4frames': Slash,
  'Track Down_2x2_4frames': Slash,
  'Treachery_2x2_4frames': Slash,
  'Truth_2x2_4frames': Slash,
  'Vicious Bite_2x2_4frames': Slash,
  'Vortex_2x2_4frames': Slash,
  'Wild Punch_2x2_4frames': Slash,
  'Wolf Claw_2x2_4frames': Slash,
  "Zeus's Wrath_2x2_4frames": Slash,
  'Chop_2x2_4frames': Slash,
  'Axe Throw_2x2_4frames': Slash,
  'Battle Projectile_2x2_4frames': Slash,
  'Force Blast_2x2_4frames': Slash,
  'Staff Finisher_2x2_frames': Slash,
};

export default registry;
export const getAnimation = (name) => registry[name];
