// src/spells.js
// Registry of spell definitions (specs reference `targeting.js` descriptors and `effects.js`)

/**
 * =============================================================================
 * SPELL CREATION GUIDE
 * =============================================================================
 * 
 * ANIMATION LENGTH:
 *   - Default animationMs should be 1200 (milliseconds)
 *   - Adjust only if the spell needs faster/slower timing
 * 
 * =============================================================================
 * SPELL SPRITE IMAGES
 * =============================================================================
 * 
 * Sprites are stored in: src/public/images/spells/
 * 
 * Naming convention: "Spell Name_2x2_4frames.png"
 *   - Most are .png files, but occasionally .jpg
 *   - ALWAYS check the folder for the actual filename
 * 
 * For buff-only spells (no attack animation):
 *   - Use 'Elixir_2x2_4frames.png' as the default animation
 * 
 * =============================================================================
 * REGISTRATION CHECKLIST
 * =============================================================================
 * 
 * When adding a new spell, register it in these files:
 * 
 * 1. src/animations/index.js
 *    - Add the animation key to the registry object
 *    - Example: 'Spell Name_2x2_4frames': Slash,
 * 
 * 2. src/spellConfigs.js
 *    - This file is AUTO-GENERATED by scripts/generate_spell_manifest.js
 *    - CRITICAL: Run the script after adding new sprite files!
 *      Command: node scripts/generate_spell_manifest.js
 *    - Or manually add config if needed:
 *      "Spell Name_2x2_4frames": { 
 *        file: "/images/spells/Spell Name_2x2_4frames.png", 
 *        frames: 4, frameWidth: 256, frameHeight: 256, 
 *        cols: 2, rows: 2, maxDisplaySize: 120 
 *      }
 *    - ⚠️ Spells will NOT work without this config entry!
 * 
 * =============================================================================
 * EFFECTS
 * =============================================================================
 * 
 * If the spell applies an effect based on its description:
 *   1. Check if the effect already exists in effects.js
 *   2. If not, add the new effect to effects.js
 *   3. Check src/public/images/effects/ for a matching effect image
 *   4. NOTIFY if an effect image is missing - it may have been forgotten!
 * 
 * Effect images are stored in: src/public/images/effects/
 *   - Usually named: "Effect Name.png"
 * 
 * =============================================================================
 * SPELL OBJECT STRUCTURE
 * =============================================================================
 * 
 * {
 *   id: 'spellId',                          // Unique camelCase identifier
 *   name: 'Spell Name',                     // Display name
 *   description: 'What the spell does',     // From card description
 *   spec: {
 *     targets: [{                           // Targeting configuration
 *       type: 'projectile|highestHealth|lowestHealth|board|column|adjacent|self|random',
 *       side: 'enemy|ally',
 *       max: 1                              // Optional: limit number of targets
 *     }],
 *     formula: {                            // Damage/heal formula
 *       type: 'attackPower|heal|fixed',
 *       value: X,
 *       ignoreArmor: true,                  // Optional
 *       ignoreSpellPower: true              // Optional
 *     },
 *     effects: [EFFECTS.EffectName],        // Optional: effects to apply
 *     animationMs: 1200,                    // Animation duration (default: 1200)
 *     post: {                               // Optional: post-spell effects
 *       moveRowBack: true,                  // Push target back
 *       bypassTriggers: true                // Skip triggered effects
 *     }
 *   },
 *   animation: 'Spell Name_2x2_4frames',    // Primary animation key
 *   animationPlacement: 'travel|inplace',   // 'travel' for projectiles, 'inplace' for AoE
 *   animationSecondary: 'Name_2x2_4frames', // Optional: secondary animation
 *   sound: '/images/sounds/Sound.mp3',      // Optional: sound effect
 *   soundVolume: 0.3                        // Optional: volume (0-1)
 * }
 * 
 * =============================================================================
 * TARGET TYPES REFERENCE
 * =============================================================================
 * 
 * - projectile: First enemy in line
 * - highestHealth: Enemy with highest current health
 * - lowestHealth: Enemy with lowest current health  
 * - board: All heroes on the board
 * - column: All heroes in the same column
 * - adjacent: Heroes adjacent to the target
 * - self: The casting hero
 * - random: Random target(s)
 * - projectilePlus1: Projectile target + 1 adjacent
 * - rowWithHighestSumArmor: Targets entire row with highest total armor
 * 
 * =============================================================================
 */

import { EFFECTS } from './effects.js';

// NOTE: `cost` properties will be authoritative in `heroes.js`. (Removed from here for clarity.)
export const SPELLS = {
  // Basic fallback attack used when a slot has no spells or has exhausted its casts.
  basicAttack: {
    id: 'basicAttack', name: 'Basic Attack',
    description: 'Fallback attack: deals 1 damage to the highest-health enemy. Ignores armor and spellPower, bypasses triggers.',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 1, ignoreArmor: true, ignoreSpellPower: true }, post: { bypassTriggers: true }, animationMs: 500 },
    sound: '/images/sounds/Basic Attack.mp3',
    soundVolume: 0.3
  },

  // Bile Creature spells
  acid: {
    id: 'acid',
    name: 'Acid',
    description: 'Targets the enemy with the highest Health, and applies an effect: Acid which does damage equal to the Round Number at the beginning of each Round.',
    spec: {
      targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }],
      effects: [EFFECTS.Acid],
      animationMs: 1200
    },
    animation: 'Acid_2x2_4frames',
    animationPlacement: 'travel'
  },

  armorMelt: {
    id: 'armorMelt',
    name: 'Armor Melt',
    description: 'Targets the enemy row with the highest sum of Armor applying an effect: Armor Melt which reduces Armor by 1 and deals 1 damage at the beginning of each turn.',
    spec: {
      targets: [{ type: 'rowWithHighestSumArmor', side: 'enemy' }],
      effects: [EFFECTS.ArmorMelt],
      animationMs: 1200
    },
    animation: 'Armor Melt_2x2_4frames',
    animationPlacement: 'inplace'
  },

  acidPool: {
    id: 'acidPool',
    name: 'Acid Pool',
    description: 'Targets the entire enemy board and applies an Effect: Burn which deals 1 damage at the beginning of each Round.',
    spec: {
      targets: [{ type: 'board', side: 'enemy' }],
      effects: [EFFECTS.Burn],
      animationMs: 1200
    },
    animation: 'Acid Pool_2x2_4frames',
    animationPlacement: 'inplace'
  },

  // Blood Golem spells
  bloodDrain: {
    id: 'bloodDrain',
    name: 'Blood Drain',
    description: 'Targets the enemy with the highest Health. If the caster has less health than the target, deal 3 Attack Power and target the caster for a Heal Power of 5. If the caster has equal or more health than the target, deal 5 Attack Power.',
    spec: {
      targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }],
      formula: { type: 'attackPower', value: 3 }, // default when caster health < target
      animationMs: 1200,
      post: {
        conditionalOnCasterVsTargetHealth: {
          // If caster health < target health: deal 3 damage + heal caster for 5
          lessThan: { damage: 3, healCaster: 5 },
          // If caster health >= target health: deal 5 damage
          greaterOrEqual: { damage: 5 }
        }
      }
    },
    animation: 'Blood Drain_2x2_4frames',
    animationPlacement: 'travel',
    animationSecondary: 'Healing_2x2_4frames'
  },
  soulLink: {
    id: 'soulLink',
    name: 'Soul Link',
    description: 'Targets the caster and applies a buff: Soul Link, which causes Blood Golem to absorb half the damage that would be taken by adjacent allies. Soul Link does not stack.',
    spec: {
      targets: [{ type: 'self' }],
      effects: [EFFECTS.SoulLink],
      animationMs: 1200
    },
    animation: 'Elixir_2x2_4frames',
    animationPlacement: 'inplace'
  },
  consumeCorpse: {
    id: 'consumeCorpse',
    name: 'Consume Corpse',
    description: 'Targets the nearest ally corpse and removes it from play. If a corpse is removed, target caster for a Heal Power of 7.',
    spec: {
      targets: [{ type: 'nearestDeadAlly', side: 'ally' }],
      formula: { type: 'healPower', value: 0 }, // no base heal
      animationMs: 1200,
      post: {
        removeCorpse: true,
        healCasterIfRemoved: 7
      }
    },
    animation: 'Healing_2x2_4frames',
    animationPlacement: 'inplace'
  },

  // Behemoth — Monster hero spells
  brutalSmash: {
    id: 'brutalSmash',
    name: 'Brutal Smash',
    description: 'Targets the enemy with the highest Armor for 6 Attack Power',
    spec: {
      targets: [{ type: 'highestArmor', side: 'enemy', max: 1 }],
      formula: { type: 'attackPower', value: 6 },
      animationMs: 1200
    },
    animation: 'Brutal Smash_2x2_4frames',
    animationPlacement: 'travel'
  },

  monstrousClaws: {
    id: 'monstrousClaws',
    name: 'Monstrous Claws',
    description: 'Targets the enemy row with the Hero with the least Armor and deals 3 Attack Power',
    spec: {
      targets: [{ type: 'rowContainingLowestArmor', side: 'enemy' }],
      formula: { type: 'attackPower', value: 3 },
      animationMs: 1200
    },
    animation: 'Monstrous Claws_2x2_4frames',
    animationPlacement: 'inplace'
  },

  berserk: {
    id: 'berserk',
    name: 'Berserk',
    description: "Targets the enemy with the highest Health, dealing 3 Attack Power plus half of Berserker's missing Health (rounded down).",
    spec: {
      targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }],
      formula: { type: 'attackPower', value: 3, addCasterMissingHealthHalf: true },
      animationMs: 1200
    },
    animation: 'Berserk_2x2_4frames',
    animationPlacement: 'travel'
  },

  roar: {
    id: 'roar',
    name: 'Roar',
    description: 'Targets the caster and applies an effect: Power which increases the casters Spell Power by 2',
    spec: {
      targets: [{ type: 'self' }],
      effects: [EFFECTS.Power],
      animationMs: 1200
    },
    animation: 'Elixir_2x2_4frames',
    animationPlacement: 'inplace'
  },

  // Fire Mage spells
  fireBomb: {
    id: 'fireBomb', name: 'Fire Bomb',
    description: '(1) Projectile dealing 5 Attack Power and applying an effect: Burn (2) Targets all tiles adjacent to the enemy hit dealing 5 Attack Power and applying an effect: Burn which deals 1 Damage at the start of each Round.',
    spec: { targets: [{ type: 'projectile', side: 'enemy', max: 1 }, { type: 'adjacent', side: 'enemy' }], formula: { type: 'attackPower', value: 5 }, effects: [EFFECTS.Burn], animationMs: 1200 },
    animation: 'Fire Bomb_2x2_4frames', animationPlacement: 'travel',
    animationSecondary: 'Fire Bomb Secondary_2x2_4frames'
  },

  fireBolt: {
    id: 'fireBolt', name: 'Fire Bolt',
    description: 'Targets the enemy with the highest Health, dealing 6 Attack Power and applying an effect: Burn which deals 1 Damage at the start of each Round.',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 6 }, effects: [EFFECTS.Burn], animationMs: 1200 },
    animation: 'Fire Bolt_2x2_4frames',
    animationPlacement: 'travel'
  },

  consumedByFlames: {
    id: 'consumedByFlames', name: 'Consumed By Flames',
    description: 'Targets the enemy with the most Burns and deals Attack Power equal to 4 + the number of Burns.',
    spec: {
      targets: [{ type: 'mostEffectName', side: 'enemy', max: 1, effectName: 'Burn' }],
      formula: { type: 'attackPower', value: 4, addTargetEffectNameCount: 'Burn', addTargetEffectCountMultiplier: 1 },
      animationMs: 1200
    },
    animation: 'Consumed By Flames_2x2_4frames',
    animationPlacement: 'travel'
  },

  heatingUp: {
    id: 'heatingUp', name: 'Heating Up',
    description: "Targets the nearest ally and applies an effect: Heating Up which causes the effected Hero's spells to apply Burn to all targeted enemies.",
    spec: { targets: [{ type: 'nearest', side: 'ally', max: 1 }], effects: [EFFECTS.HeatingUp], animationMs: 1200 },
    animation: 'Elixir_2x2_4frames',
    animationPlacement: 'inplace'
  },

  consumeBurn: {
    id: 'consumeBurn', name: 'Consume Burn',
    description: 'Targets the enemy with the most Burns and removes the topmost Burn. If a Burn is removed, deal 4 Attack Power to the enemy and heal the caster for 4.',
    spec: {
      targets: [{ type: 'mostEffectName', side: 'enemy', max: 1, effectName: 'Burn' }],
      post: { removeTopEffectByName: { name: 'Burn', onRemoved: { damageTarget: 4, healCaster: 4 } } },
      animationMs: 1200
    },
    animation: 'Consume Burn_2x2_4frames',
    animationPlacement: 'travel'
  },

  meteor: {
    id: 'meteor', name: 'Meteor',
    description: 'Targets the entire enemy board, dealing 6 Attack Power.',
    spec: { targets: [{ type: 'board', side: 'enemy' }], formula: { type: 'attackPower', value: 6 }, animationMs: 1200 },
    animation: 'Blaze_2x2_4frames', animationPlacement: 'inplace'
  },

  // wildfireTrap and pyreBlast (commented out - Flamewright not active)
  /*
  wildfireTrap: { id: 'wildfireTrap', name: 'Wildfire Trap', description: 'Places a turret that fires a 3-damage projectile for 3 rounds.', spec: { targets: [{ type: 'self' }], effects: [EFFECTS.WildfireTurret], animationMs: 500 } },
  pyreBlast: { id: 'pyreBlast', name: 'Pyre Blast', description: 'Deals 6 Attack Power to column and applies Burn.', spec: { targets: [{ type: 'projectilePlus1', side: 'enemy' }], formula: { type: 'attackPower', value: 6 }, effects: [EFFECTS.Burn], animationMs: 1200 }, animation: 'Fire Breath_2x2_4frames', animationPlacement: 'travel' },
  */

  // Shieldbearer (commented out - no active hero)
  /*
  shieldBash: { id: 'shieldBash', name: 'Shield Bash', description: 'Deals 2 Attack Power and slows target.', spec: { targets: [{ type: 'projectile', side: 'enemy' }], formula: { type: 'attackPower', value: 2 }, effects: [EFFECTS.Slowed], animationMs: 1200 }, animation: 'Charge_2x2_4frames', animationPlacement: 'travel' },
  */
  // Knight spells
  charge: {
    id: 'charge', name: 'Charge',
    description: 'Projectile which deals 4 Attack Power and moves the targeted Hero back 1 row if available.',
    spec: { targets: [{ type: 'projectile', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 4 }, animationMs: 1200, post: { moveRowBack: true } },
    animation: 'Charge_2x2_4frames', animationPlacement: 'travel'
  },
  counter: {
    id: 'counter', name: 'Counter',
    description: 'Targets the caster and applies Counter: deals 2 damage to any enemy who damages the effected Hero with a spell.',
    spec: { targets: [{ type: 'self' }], effects: [EFFECTS.Counter], animationMs: 1200 },
    animation: 'Counter_2x2_4frames',
    animationPlacement: 'inplace'
  },
    boulder: {
      id: 'boulder', name: 'Boulder',
      description: 'Targets the enemy with the highest Health, dealing 6 Attack Power.',
      spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 6 }, animationMs: 1200 },
      animation: 'Boulder_2x2_4frames',
      animationPlacement: 'travel'
    },

    vortex: {
      id: 'vortex', name: 'Vortex',
      description: 'Targets the enemy with the highest Speed, dealing 4 Attack Power ignoring Armor.',
      spec: { targets: [{ type: 'highestSpeed', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 4, ignoreArmor: true }, animationMs: 1200 },
      animation: 'Vortex_2x2_4frames',
      animationPlacement: 'travel'
    },

    blaze: {
      id: 'blaze', name: 'Blaze',
      description: 'Targets the entire enemy board, dealing 4 Attack Power to each.',
      spec: { targets: [{ type: 'board', side: 'enemy' }], formula: { type: 'attackPower', value: 4 }, animationMs: 1200 },
      animation: 'Blaze_2x2_4frames',
      animationPlacement: 'inplace'
    },

  // guardUp and bulwarkField (commented out - Shieldbearer not active)
  /*
  guardUp: { id: 'guardUp', name: 'Guard Up', description: 'Give an ally +3 Armor for 2 rounds.', spec: { targets: [{ type: 'projectile', side: 'ally' }], effects: [EFFECTS.Shielded], animationMs: 1200 }, animation: 'Iron Forge_2x2_4frames', animationPlacement: 'inplace' },
  bulwarkField: { id: 'bulwarkField', name: 'Bulwark Field', description: 'Applies +1 Armor and +1 Speed to all allies for 2 rounds.', spec: { targets: [{ type: 'board', side: 'ally' }], effects: [EFFECTS.BulwarkAura], animationMs: 1200 }, animation: 'Iron Forge_2x2_4frames', animationPlacement: 'inplace' },
  */

  // Hamstring: targets highest Speed enemy, deals 3 and applies Slowed (-1 Speed)
  hamstring: {
    id: 'hamstring', name: 'Hamstring',
    description: 'Targets the enemy with the highest Speed, dealing 3 Attack Power and applying Slowed (-1 Speed).',
    spec: { targets: [{ type: 'highestSpeed', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 3 }, effects: [EFFECTS.Slowed], animationMs: 1200 },
    animation: 'Hamstring_2x2_4frames',
    animationPlacement: 'travel'
  },

  // Battle Mage spells (new)
  forceBlast: {
    id: 'forceBlast', name: 'Force Blast',
    description: "Targets the enemy with the highest Armor for 9 Attack Power and grants the caster +4 Energy.",
    spec: { targets: [{ type: 'highestArmor', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 9 }, post: { deltaEnergy: { amount: 4, side: 'ally', target: 'self' } }, animationMs: 1200 },
    animation: 'Force Blast_2x2_4frames', animationPlacement: 'travel'
  },

  staffFinisher: {
    id: 'staffFinisher', name: 'Staff Finisher',
    description: 'Targets the enemy with the lowest Health, dealing 2 Attack Power (ignores Armor).',
    spec: { targets: [{ type: 'lowestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 2, ignoreArmor: true }, animationMs: 1200 },
    animation: 'Staff Finisher_2x2_frames', animationPlacement: 'travel'
  },

  battle: {
    id: 'battle', name: 'Battle',
    description: 'A projectile dealing 3 attack power (ignores armor) to the primary target and 5 attack power to a secondary target with the highest health.',
    // Two targets: 0 => projectile (primary animation), 1 => highestHealth (secondary animation)
    spec: {
      targets: [
        { type: 'projectile', side: 'enemy', max: 1 },
        { type: 'highestHealth', side: 'enemy', max: 1 }
      ],
      // Default formula will be overridden per-target via perTargetExtras below
      formula: { type: 'attackPower', value: 0 },
      // Provide per-target payload overrides: part 1 = 3 damage ignoring armor, part 2 = 5 damage
      perTargetExtras: [
        { action: 'damage', value: 3, ignoreArmor: true },
        { action: 'damage', value: 5 }
      ],
      animationMs: 1200
    },
    animation: 'Battle Projectile_2x2_4frames',
    animationSecondary: 'Slash_2x2_4frames',
    animationPlacement: 'travel'
  },

  // Lightning Mage spells (from provided card)
  forkedLightning: {
    id: 'forkedLightning', name: 'Forked Lightning',
    description: 'Targets the nearest 3 enemies for 5 Attack Power.',
    spec: { targets: [{ type: 'nearest', side: 'enemy', max: 3 }], formula: { type: 'attackPower', value: 5 }, animationMs: 1200 },
    animation: 'Forked Lightning_2x2_4frames',
    animationPlacement: 'inplace'
  },

  lightningBolt: {
    id: 'lightningBolt', name: 'Lightning Bolt',
    description: 'Targets the enemy with the highest Health dealing 7 Attack Power and applies Static Shock (adjacent damage each round).',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 7 }, effects: [EFFECTS.StaticShock], animationMs: 1200 },
    animation: 'Lightning Bolt_2x2_4frames',
    animationPlacement: 'travel'
  },

  zeusWrath: {
    id: 'zeusWrath', name: "Zeus' Wrath",
    description: "Targets the entire enemy board for 10 Attack Power.",
    spec: { targets: [{ type: 'board', side: 'enemy' }], formula: { type: 'attackPower', value: 10 }, animationMs: 1200 },
    animation: "Zeus's Wrath_2x2_4frames",
    animationPlacement: 'inplace'
  },


  // Lancer (new)
  slash: {
    id: 'slash', name: 'Slash',
    description: 'Targets the enemy with the highest Health, dealing 5 Attack Power.',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy' }], formula: { type: 'attackPower', value: 5 }, animationMs: 1200 },
    animation: 'Slash_2x2_4frames',
    animationPlacement: 'travel',
    sound: '/images/sounds/Slash.mp3',
    soundVolume: 0.3
  },
  // Jester (new) -- front: copies last enemy cast; middle: slash; back: special conditional
  copyCat: {
    id: 'copyCat', name: 'Copy Cat',
    description: 'Performs the last spell cast by an enemy Hero, as though this hero is the caster (if any).',
    // Note: this is a special-case spell handled in the engine; spec provided mainly for animation placement
    spec: { targets: [{ type: 'self' }], animationMs: 500 }
  },
  oops: {
    id: 'oops', name: 'OOPS!!',
    description: 'Targets an ally with the lowest Health, dealing 3 Attack Power ignoring Armor. If this would kill that ally, deal 999 Attack Power to the enemy with the highest Health.',
    spec: {
      targets: [{ type: 'lowestHealth', side: 'ally', max: 1 }],
      formula: { type: 'attackPower', value: 3, ignoreArmor: true },
      post: {
        // Engine will check this after computing deferred changes and, if the chosen ally would die,
        // run the `secondarySpec` as an additional deferred attack from the original caster.
        conditionalSecondaryOnWouldKill: {
          secondarySpec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 999 } }
        }
      },
      animationMs: 1200
    },
    animation: 'Oops_2x2_4frames',
    animationPlacement: 'travel',
    animationSecondary: 'Oops Secondary_2x2_4frames'
  },

  // Drunkard
  barrelSmash: {
    id: 'barrelSmash', name: 'Barrel Smash',
    description: 'Targets the enemy with the highest Speed, dealing 5 Attack Power and applying Slowed (-1 Speed).',
    spec: { targets: [{ type: 'highestSpeed', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 5 }, effects: [EFFECTS.Slowed], animationMs: 1200 },
    animation: 'Barrel Smash_2x2_4frames',
    animationPlacement: 'travel'
  },
  wildPunch: {
    id: 'wildPunch', name: 'Wild Punch',
    description: 'Targets the enemy with the highest Health, dealing attack power equal to 2 + d6.',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'roll', base: 2, die: 6 }, animationMs: 1200 },
    animation: 'Wild Punch_2x2_4frames',
    animationPlacement: 'travel'
  },
  specialBrew: {
    id: 'specialBrew', name: 'Special Brew',
    description: 'Targets allied back-row heroes and increases their Energy by 2.',
    spec: { targets: [{ type: 'backRow', side: 'ally' }], post: { deltaEnergy: 2 }, animationMs: 1200 },
    animation: 'Special Brew_2x2_4frames',
    animationPlacement: 'inplace'
  },
  pierce: {
    id: 'pierce', name: 'Pierce',
    description: 'Column attack dealing 4 Attack Power.',
    spec: { targets: [{ type: 'column', side: 'enemy' }], formula: { type: 'attackPower', value: 4 }, animationMs: 1200 },
    animation: 'Pierce_2x2_4frames',
    animationPlacement: 'travel'
  },
  javelin: {
    id: 'javelin', name: 'Javelin',
    description: 'Targets the first enemy encountered via reverse book reading, dealing 4 Attack Power and applies Bleed.',
    spec: { targets: [{ type: 'reverseBook', side: 'enemy' }], formula: { type: 'attackPower', value: 4 }, effects: [EFFECTS.Bleed], animationMs: 1200 },
    animation: 'Javelin_2x2_4frames',
    animationPlacement: 'travel'
  },

  // Angel
  lightPillar: {
    id: 'lightPillar', name: 'Light Pillar',
    description: 'Column attack dealing 4 Attack Power and removing the top positive effect.',
    spec: { targets: [{ type: 'column', side: 'enemy' }], formula: { type: 'attackPower', value: 4 }, post: { removeTopPositiveEffect: true }, animationMs: 1200 },
    animation: 'Light Pillar_2x2_4frames',
    animationPlacement: 'travel'
  },

  // Arcane Mage
  arcaneExplosion: {
    id: 'arcaneExplosion', name: 'Arcane Explosion',
    description: '(1) Targets the enemy with the most positive effects and removes the topmost effect and deals 6 Attack Power. (2) Also hits adjacent enemies for 6 Attack Power.',
    spec: { targets: [{ type: 'mostBuffs', side: 'enemy', max: 1 }, { type: 'adjacent', side: 'enemy' }], formula: { type: 'attackPower', value: 6 }, post: {}, 
      perTargetExtras: [ { post: { removeTopPositiveEffect: true } }, {} ], animationMs: 1200 },
    // Use a primary animation for the main target and a secondary for adjacent targets
    animation: 'Arcane Explosion_2x2_4frames',
    animationSecondary: 'Arcane Explosion Secondary_2x2_4frames',
    animationPlacement: 'travel'
  },

  // Ice Mage spells removed from here - see end of file
  arcaneBolt: { id: 'arcaneBolt', name: 'Arcane Bolt', description: 'Targets the enemy with the lowest Health, dealing 5 Attack Power.', spec: { targets: [{ type: 'lowestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 5 }, animationMs: 1200 }, animation: 'Arcane Bolt_2x2_4frames', animationPlacement: 'travel' },
  arcaneBlast: { id: 'arcaneBlast', name: 'Arcane Blast', description: 'Targets the enemy with the highest Health, dealing 15 Attack Power.', spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 15 }, animationMs: 1000 }, animation: 'Arcane Blast_2x2_4frames', animationPlacement: 'travel' },

  prayer: {
    id: 'prayer', name: 'Prayer',
    description: 'Targets the caster and applies Prayer: heals all allies except the effected Hero by 1 each time the effected Hero is damaged.',
    spec: { targets: [{ type: 'self' }], effects: [EFFECTS.Prayer], animationMs: 1200 },
    animation: 'Prayer_2x2_4frames',
    animationPlacement: 'inplace'
  },

  // Enchantress spells (use exact card text in descriptions)
  enchantDexterity: {
    id: 'enchantDexterity', name: 'Enchant Dexterity',
    description: 'Targets the ally with the least combined Speed and Armor with a Heal Power of 2 and gives the effect: Dexterity which increases armor and speed by 1.',
    spec: { targets: [{ type: 'leastSpeedAndArmor', side: 'ally', max: 1 }], formula: { type: 'healPower', value: 2 }, effects: [EFFECTS.Dexterity], animationMs: 1200 },
    animation: 'Healing_2x2_4frames',
    animationPlacement: 'inplace'
  },

  enchantStamina: {
    id: 'enchantStamina', name: 'Enchant Stamina',
    description: 'Targets the ally with least effects and applies and effect: Regen which increases 1 at the end of each turn.',
    spec: { targets: [{ type: 'leastEffects', side: 'ally', max: 1 }], effects: [EFFECTS.Regen], animationMs: 1200 },
    animation: 'Elixir_2x2_4frames',
    animationPlacement: 'inplace'
  },

  enchantStrength: {
    id: 'enchantStrength', name: 'Enchant Strength',
    description: 'Targets the ally with least effects (cannot target caster) and applies and effect: Strength which increases Spell Power by 1.',
    spec: { targets: [{ type: 'leastEffects', side: 'ally', max: 1, excludeSelf: true }], effects: [EFFECTS.Strength], animationMs: 1200 },
    animation: 'Elixir_2x2_4frames',
    animationPlacement: 'inplace'
  },

  // Demon: Death Pact — apply an effect that reflects damage back to the attacker
  deathPact: {
    id: 'deathPact', name: 'Death Pact',
    description: 'Targets the caster and applies Death Pact: when the effected Hero is damaged by an enemy spell, equal damage is returned to the attacker.',
    spec: { targets: [{ type: 'self' }], effects: [EFFECTS.DeathPact], animationMs: 1200 },
    animation: 'Death Pact_2x2_4frames',
    animationPlacement: 'inplace'
  },

  // Demon: Siphon — damage enemy and heal caster
  siphon: {
    id: 'siphon', name: 'Siphon',
    description: 'Targets the enemy with the highest Health, dealing 4 Attack Power. Also heals the caster for 4.',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }, { type: 'self' }], formula: { type: 'attackPower', value: 4 }, post: { secondaryHeal: { amount: 4, side: 'ally', target: 'self' } }, animationMs: 1200 },
    animation: 'Siphon_2x2_4frames', animationPlacement: 'travel', animationSecondary: 'Healing_2x2_4frames'
  },

  // Demon: Curse — applies a debuff that reduces Spell Power by 1 and deals 3 damage ignoring Armor
  curse: {
    id: 'curse', name: 'Curse',
    description: 'Targets the enemy with the least effects, dealing 3 Attack Power ignoring Armor and applying Curse (-1 Spell Power).',
    spec: { targets: [{ type: 'leastEffects', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 3, ignoreArmor: true }, effects: [EFFECTS.Curse], animationMs: 1200 },
    animation: 'Curse_2x2_4frames',
    animationPlacement: 'travel'
  },
  rage: {
    id: 'rage',
    name: 'Rage',
    description: 'Targets the caster, dealing 2 Damage and applying an effect: Power which increases Spell Power by 2.',
    spec: {
      targets: [{ type: 'self' }],
      formula: { type: 'damage', value: 2 },
      effects: [EFFECTS.Power],
      animationMs: 800
    },
    animation: 'Rage_2x2_4frames',
    animationPlacement: 'inplace'
  },
  // Blacksmith
  hammer: {
    id: 'hammer', name: 'Hammer',
    description: 'Targets the enemy with the highest Energy, dealing 5 Attack Power.',
    spec: { targets: [{ type: 'highestEnergy', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 5 }, animationMs: 1200 },
    animation: 'Hammer_2x2_4frames',
    animationPlacement: 'travel'
  },
  justice: {
    id: 'justice', name: 'Justice',
    description: 'Targets the enemy with the highest Energy, dealing 6 Attack Power.',
    spec: { targets: [{ type: 'highestEnergy', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 6 }, animationMs: 1200 },
    animation: 'Hammer_2x2_4frames',
    animationPlacement: 'travel'
  },
  armorUp: {
    id: 'armorUp', name: 'Armor Up',
    description: 'Targets the ally with the least Armor and applies Armor Up (+2 Armor).',
    spec: { targets: [{ type: 'leastArmor', side: 'ally', max: 1 }], effects: [EFFECTS.ArmorUp], animationMs: 1200 },
    animation: 'Iron Forge_2x2_4frames',
    animationPlacement: 'inplace'
  },
  humble: {
    id: 'humble', name: 'Humble',
    description: 'Targets the enemy with the most positive effects, dealing 4 Attack Power plus 2× the number of positive effects.',
    spec: { targets: [{ type: 'mostBuffs', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 4, addTargetEffectsMultiplier: 2 }, animationMs: 1200 },
    animation: 'Humiliation_2x2_4frames',
    animationPlacement: 'travel'
  },
  ironForge: {
    id: 'ironForge', name: 'Iron Forge',
    description: 'Targets the ally with the least Armor and applies Iron Forge (+1 Armor, +1 SpellPower).',
    spec: { targets: [{ type: 'leastArmor', side: 'ally', max: 1 }], effects: [EFFECTS.IronForge], animationMs: 1200 },
    animation: 'Iron Forge_2x2_4frames',
    animationPlacement: 'travel'
  },
  moltenPour: {
    id: 'moltenPour', name: 'Molten Pour',
    description: 'Targets the row containing the enemy with the highest Armor, dealing 3 Attack Power ignoring Armor.',
    spec: { targets: [{ type: 'rowContainingHighestArmor', side: 'enemy' }], formula: { type: 'attackPower', value: 3, ignoreArmor: true }, animationMs: 1200 },
    animation: 'Molten Pour_2x2_4frames',
    animationPlacement: 'inplace'
  },

  // Elder (new)
  malign: {
    id: 'malign', name: 'Malign',
    description: 'Targets the enemy with the highest Energy, dealing 7 Attack Power and reducing their Energy by 1.',
    spec: { targets: [{ type: 'highestEnergy', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 7 }, post: { deltaEnergy: -1 }, animationMs: 1200 },
    animation: 'Malign_2x2_4frames',
    animationPlacement: 'travel'
  },

  humility: {
    id: 'humility', name: 'Humility',
    description: 'Targets the enemy with the most positive effects, dealing 5 Attack Power and removing the top positive effect.',
    spec: { targets: [{ type: 'mostBuffs', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 5 }, post: { removeTopPositiveEffect: true }, animationMs: 1200 },
    animation: 'Humiliation_2x2_4frames',
    animationPlacement: 'travel'
  },

  truth: {
    id: 'truth', name: 'Truth',
    description: 'Targets all enemies who currently have any negative effects, dealing 6 Attack Power.',
    spec: { targets: [{ type: 'board', side: 'enemy' }], formula: { type: 'attackPower', value: 6 }, post: { onlyApplyIfHasDebuff: true }, animationMs: 1200 },
    animation: 'Truth_2x2_4frames',
    animationPlacement: 'inplace'
  },

  // Archer
  multishot: {
    id: 'multishot', name: 'Multishot',
    description: 'Targets (1) lowest Health, (2) highest Health, (3) lowest Armor enemy, dealing 4 Attack Power to each.',
    spec: { targets: [
      { type: 'lowestHealth', side: 'enemy' },
      { type: 'highestHealth', side: 'enemy' },
      { type: 'leastArmor', side: 'enemy' }
    ], formula: { type: 'attackPower', value: 4 }, animationMs: 1200 },
    animation: 'Multi Shot_2x2_4frames',
    animationPlacement: 'travel'
  }
,
  // Huntress spells (from provided card)
  lieInWait: {
    id: 'lieInWait', name: 'Lie In Wait',
    description: 'Grants an ally +2 Spell Power and makes them untargetable by single-target spells for 5 rounds.',
    spec: { targets: [{ type: 'self', side: 'ally' }], effects: [EFFECTS.LieInWait], animationMs: 1200 }, animation: 'Elixir_2x2_4frames', animationPlacement: 'inplace'
  },
  spear: {
    id: 'spear', name: 'Spear',
    description: 'Projectile dealing 8 Attack Power.',
    spec: { targets: [{ type: 'projectile', side: 'enemy' }], formula: { type: 'attackPower', value: 8 }, animationMs: 1200 }, animation: 'Spear_2x2_4frames', animationPlacement: 'travel'
  },
  blowDart: {
    id: 'blowDart', name: 'Blow Dart',
    description: 'Projectile dealing 4 Attack Power and applying Poison.',
    spec: { targets: [{ type: 'projectile', side: 'enemy' }], formula: { type: 'attackPower', value: 4 }, effects: [EFFECTS.Poison], animationMs: 1200 },
    animation: 'Blow Dart_2x2_4frames',
    animationPlacement: 'travel'
  },
  arrow: {
    id: 'arrow', name: 'Arrow',
    description: 'Targets the enemy with the highest Health, dealing 5 Attack Power.',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy' }], formula: { type: 'attackPower', value: 5 }, animationMs: 1200 },
    animation: 'Arrow_2x2_4frames',
    animationPlacement: 'travel'
  },

  deadEye: {
    id: 'deadEye', name: 'Dead Eye',
    description: 'Projectile dealing 10 Attack Power to a single target.',
    spec: { targets: [{ type: 'projectile', side: 'enemy' }], formula: { type: 'attackPower', value: 10 }, animationMs: 1200 },
    animation: 'Dead Eye_2x2_4frames',
    animationPlacement: 'travel'
  },

  // Assassin (new)
  poisonDagger: {
    id: 'poisonDagger', name: 'Poison Dagger',
    description: 'Targets the enemy with the highest Health dealing 5 Attack Power and applying Poison.',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy' }], formula: { type: 'attackPower', value: 5 }, effects: [EFFECTS.Poison], animationMs: 1200 },
    animation: 'Poison Dagger_2x2_4frames',
    animationPlacement: 'travel'
  },

  // Apothecary spells
  vitalityPotion: {
    id: 'vitalityPotion', name: 'Vitality Potion',
    description: 'Targets the ally with the lowest Health and heals them for 7 (+spellPower). Also grants Strength (spellPower +1).',
    spec: { targets: [{ type: 'lowestHealth', side: 'ally', max: 1 }], formula: { type: 'healPower', value: 7 }, effects: [EFFECTS.Strength], animationMs: 1200 },
    animation: 'Healing_2x2_4frames', animationPlacement: 'inplace'
  },

  brimberryLeaves: {
    id: 'brimberryLeaves', name: 'Brimberry Leaves',
    description: 'Targets the ally with the most negative effects, removes one negative effect and increases their Energy by 2.',
    spec: { targets: [{ type: 'mostDebuffs', side: 'ally', max: 1 }], post: { removeTopDebuff: true, deltaEnergy: 2 }, animationMs: 1200 },
    animation: 'Brimberry Leaves_2x2_4frames',
    animationPlacement: 'travel'
  },

  assassinate: {
    id: 'assassinate', name: 'Assassinate',
    description: 'Deals 7 Attack Power to all enemies with Mark.',
    spec: { targets: [{ type: 'board', side: 'enemy' }], formula: { type: 'attackPower', value: 7 }, post: { onlyApplyToWithEffect: 'Marked' }, animationMs: 1200 },
    animation: 'Assassinate_2x2_4frames',
    animationPlacement: 'inplace'
  },

  priorityTarget: {
    id: 'priorityTarget', name: 'Priority Target',
    description: 'Targets the enemy with the most positive (buff) effects, dealing 8 Attack Power.',
    spec: { targets: [{ type: 'mostBuffs', side: 'enemy' }], formula: { type: 'attackPower', value: 8 }, animationMs: 1200 },
    animation: 'Priority Target_2x2_4frames',
    animationPlacement: 'travel'
  },

  // Bounty Hunter spells
  arrest: {
    id: 'arrest', name: 'Arrest',
    description: 'Targets the enemy with the lowest Health, dealing 6 Attack Power.',
    spec: { targets: [{ type: 'lowestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 6 }, animationMs: 1200 },
    animation: 'Arrest_2x2_4frames',
    animationPlacement: 'travel'
  },

  sneakAttack: {
    id: 'sneakAttack', name: 'Sneak Attack',
    description: 'Targets the enemy first encountered according to a reverse book reading, dealing 5 Attack Power.',
    spec: { targets: [{ type: 'reverseBook', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 5 }, animationMs: 1200 },
    animation: 'Sneak attack_2x2_4frames',
    animationPlacement: 'travel'
  },

  trackDown: {
    id: 'trackDown', name: 'Track Down',
    description: 'Targets the enemy with the highest Speed, dealing 7 Attack Power.',
    spec: { targets: [{ type: 'highestSpeed', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 7 }, animationMs: 1200 },
    animation: 'Track Down_2x2_4frames',
    animationPlacement: 'travel'
  },

  // Alchemist
  experimentalToxin: {
    id: 'experimentalToxin', name: 'Experimental Toxin',
    description: 'Damages the enemy with least Armor for 1 + d6.',
    spec: { targets: [{ type: 'leastArmor', side: 'enemy' }], formula: { type: 'roll', base: 1, die: 6 }, animationMs: 1200 }, animation: 'Experimental Toxin_2x2_4frames', animationPlacement: 'travel' },
  elixir: {
    id: 'elixir', name: 'Elixir',
    description: 'Removes all debuffs from an ally and grants a permanent Elixir buff (+1 Speed, +1 Armor, +1 SpellPower).',
    spec: { targets: [{ type: 'mostDebuffs', side: 'ally' }], effects: [EFFECTS.Elixir], post: { removeDebuffs: true }, animationMs: 1200 }, animation: 'Elixir_2x2_4frames', animationPlacement: 'inplace' },
  bombToss: {
    id: 'bombToss', name: 'Bomb Toss',
    description: 'Throws a bomb (projectilePlus1) dealing 6 Attack Power and applying Burn (1) to affected tiles.',
    spec: { targets: [{ type: 'projectilePlus1', side: 'enemy' }], formula: { type: 'attackPower', value: 6 }, effects: [EFFECTS.Burn], animationMs: 1200 }, animation: 'Bomb Toss_2x2_4frames', animationPlacement: 'travel', animationSecondary: 'Bomb Toss Secondary_2x2_4frames' },


  // Blood Mage
  leech: {
    id: 'leech', name: 'Leech',
    description: 'Targets the enemy with the least effects and applies Leech (3 damage at start of each round).',
    spec: { targets: [{ type: 'leastEffects', side: 'enemy', max: 1 }], effects: [EFFECTS.Leech], animationMs: 1200 },
    animation: 'Leech_2x2_4frames',
    animationPlacement: 'travel'
  },
  cut: {
    id: 'cut', name: 'Cut',
    description: 'Targets the enemy with the highest Health, dealing 5 Attack Power and applying Bleed.',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 5 }, effects: [EFFECTS.Bleed], animationMs: 1200 },
    animation: 'Cut_2x2_4frames',
    animationPlacement: 'travel'
  },
  transfusion: {
    id: 'transfusion', name: 'Transfusion',
    description: 'Targets enemy with the highest Health, dealing 4 Attack Power. Also targets the ally with the lowest Health with a Heal Power of 4.',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }, { type: 'lowestHealth', side: 'ally', max: 1 }], formula: { type: 'attackPower', value: 4 }, post: { secondaryHeal: { amount: 4, side: 'ally', target: 'lowestHealth' } }, animationMs: 1200 },
    animation: 'Slash_2x2_4frames', animationPlacement: 'travel', animationSecondary: 'Healing_2x2_4frames'
  }
  ,

  // Dark Mage spells
  drain: {
    id: 'drain', name: 'Drain',
    description: "Targets the enemy with the highest Armor, dealing 5 Attack Power (ignores Armor). Also heals the caster for 5.",
    spec: { targets: [{ type: 'highestArmor', side: 'enemy', max: 1 }, { type: 'self' }], formula: { type: 'attackPower', value: 5, ignoreArmor: true }, post: { secondaryHeal: { amount: 5, side: 'ally', target: 'self' } }, animationMs: 1200 },
    animation: 'Drain_2x2_4frames', animationPlacement: 'travel', animationSecondary: 'Healing_2x2_4frames'
  },

  darkBolt: {
    id: 'darkBolt', name: 'Dark Bolt',
    description: 'Targets the enemy with the highest Health, dealing 6 Attack Power (ignores Armor).',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 6, ignoreArmor: true }, animationMs: 1200 },
    animation: 'Dark Bolt_2x2_4frames',
    animationPlacement: 'travel'
  },

  gravity: {
    id: 'gravity', name: 'Gravity',
    description: "Targets the entire enemy board, dealing Attack Power equal to 3 plus the target's Armor (ignores Armor).",
    spec: { targets: [{ type: 'board', side: 'enemy' }], formula: { type: 'attackPower', value: 3, ignoreArmor: true, addTargetArmor: true }, animationMs: 1200 },
    animation: 'Gravity_2x2_4frames',
    animationPlacement: 'inplace'
  },

  // Dark Knight spells
  darkSlash: {
    id: 'darkSlash', name: 'Dark Slash',
    description: 'Targets the enemy with the highest Health, dealing 3 Attack Power ignoring Armor.',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 3, ignoreArmor: true }, animationMs: 1200 },
    animation: 'Dark Slash_2x2_4frames',
    animationPlacement: 'travel'
  },

  soulCrush: {
    id: 'soulCrush', name: 'Soul Crush',
    description: "Targets the enemy with the highest Armor, dealing Attack Power equal to 3 + the target's Armor (ignores Armor).",
    spec: { targets: [{ type: 'highestArmor', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 3, ignoreArmor: true, addTargetArmor: true }, animationMs: 1200 },
    animation: 'Soul Crush_2x2_4frames',
    animationPlacement: 'travel'
  },

  treachery: {
    id: 'treachery', name: 'Treachery',
    description: 'Projectile that applies Treachery: deals damage equal to the Armor of the affected Hero at the start of each Round.',
    spec: { targets: [{ type: 'projectile', side: 'enemy' }], effects: [EFFECTS.Treachery], animationMs: 1200 },
    animation: 'Treachery_2x2_4frames',
    animationPlacement: 'travel'
  }
  ,
  // Dragon spells
  dragonFangs: {
    id: 'dragonFangs', name: 'Dragon Fangs',
    description: 'Targets the Enemy with the highest Health and deals 4 Attack Power.',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 4 }, animationMs: 1200 },
    animation: 'Dragon Fangs_2x2_4frames',
    animationPlacement: 'travel'
  },

  // Green Dragon spells
  gale: {
    id: 'gale', name: 'Gale',
    description: 'Targets the entire enemy board and moves them to the backmost available row.',
    spec: { targets: [{ type: 'board', side: 'enemy' }], post: { moveAllBack: true }, animationMs: 1200 },
    animation: 'Gale_2x2_4frames',
    animationPlacement: 'inplace'
  },

  viciousBite: {
    id: 'viciousBite', name: 'Vicious Bite',
    description: 'Targets the enemy with the highest Health, dealing 6 Attack Power and applies an effect: Poison which deals 2 damage at the start of each Round.',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 6 }, effects: [EFFECTS.Poison], animationMs: 1200 },
    animation: 'Vicious Bite_2x2_4frames',
    animationPlacement: 'travel'
  },

  poisonBreath: {
    id: 'poisonBreath', name: 'Poison Breath',
    description: 'Column attack that applies Poison which deals 2 damage at the start of each Round.',
    spec: { targets: [{ type: 'column', side: 'enemy' }], formula: { type: 'attackPower', value: 0 }, effects: [EFFECTS.Poison], animationMs: 1200 },
    animation: 'Poison Breath_2x2_4frames',
    animationPlacement: 'travel'
  },

  // Geisha spells
  fan: {
    id: 'fan', name: 'Fan',
    description: 'Targets the frontmost enemy row that has at least 1 Hero and move all Heroes back 1 row if available.',
    spec: { targets: [{ type: 'frontmostRowWithHero', side: 'enemy' }], post: { moveRowBack: true }, animationMs: 1200 },
    animation: 'Fan_2x2_4frames',
    animationPlacement: 'inplace'
  },

  slap: {
    id: 'slap', name: 'Slap',
    description: 'Targets the enemy with the Highest Health dealing 6 Attack Power and decreases their number of spell casts by 1 for the row the target is in.',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 6 }, post: { reduceRowCastsBy: 1 }, animationMs: 1200 },
    animation: 'Slap_2x2_4frames',
    animationPlacement: 'travel'
  },

  poisonedHairpin: {
    id: 'poisonedHairpin', name: 'Poisoned Hairpin',
    description: 'Targets the enemy with the least effects dealing 7 Attack Power and applying an effect: Poison which deals 2 damage at the start of each Round.',
    spec: { targets: [{ type: 'leastEffects', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 7 }, effects: [EFFECTS.Poison], animationMs: 1200 },
    animation: 'Blow Dart_2x2_4frames',
    animationPlacement: 'travel'
  },
  dragonsClaw: {
    id: 'dragonsClaw', name: "Dragon's Claw",
    description: 'Targets the Enemy with the lowest Armor and deals 3 Attack Power.',
    spec: { targets: [{ type: 'leastArmor', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 3 }, animationMs: 1200 },
    animation: 'Dragons Claw_2x2_4frames',
    animationPlacement: 'travel'
  },
  fireBreath: {
    id: 'fireBreath', name: 'Fire Breath',
    description: 'Column attack dealing 4 Attack Power and applies Burn (1) to affected tiles.',
    spec: { targets: [{ type: 'column', side: 'enemy' }], formula: { type: 'attackPower', value: 4 }, effects: [EFFECTS.Burn], animationMs: 1200 },
    animation: 'Fire Breath_2x2_4frames',
    animationPlacement: 'travel'
  },
  // Druid spells
  bearSwipe: {
    id: 'bearSwipe', name: 'Bear Swipe',
    description: 'Targets the Enemy with the highest Speed and deals 4 Attack Power.',
    spec: { targets: [{ type: 'highestSpeed', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 4 }, animationMs: 1200 },
    animation: 'Bear Swipe_2x2_4frames',
    animationPlacement: 'travel'
  },
  wolfClaw: {
    id: 'wolfClaw', name: 'Wolf Claw',
    description: 'Targets the enemy with the highest Health, dealing 4 Attack Power and applying Bleed (1).',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 4 }, effects: [EFFECTS.Bleed], animationMs: 1200 },
    animation: 'Wolf Claw_2x2_4frames',
    animationPlacement: 'travel'
  },
  rejuvenate: {
    id: 'rejuvenate', name: 'Rejuvenate',
    description: 'Targets the ally with the Lowest Health for a Heal Power of 1 (+spellPower) and applies Rejuvenate which heals 2 at the start of each round for 10 rounds.',
    spec: { targets: [{ type: 'lowestHealth', side: 'ally', max: 1 }], formula: { type: 'healPower', value: 1 }, effects: [EFFECTS.Rejuvenate], animationMs: 1200 },
    animation: 'Healing_2x2_4frames', animationPlacement: 'inplace'
  },
  // Cleric spells
  purify: {
    id: 'purify', name: 'Purify',
    description: 'Targets the enemy with the most positive effects, dealing 5 Attack Power and removing the top positive effect.',
    spec: { targets: [{ type: 'mostBuffs', side: 'enemy' }], formula: { type: 'attackPower', value: 5 }, post: { removeTopPositiveEffect: true }, animationMs: 1200 },
    animation: 'Purify_2x2_4frames',
    animationPlacement: 'travel'
  },
  cleanse: {
    id: 'cleanse', name: 'Cleanse',
    description: 'Targets the ally with the most negative effects and removes the top negative effect; heals for 2 if a negative effect was removed.',
    spec: { targets: [{ type: 'mostDebuffs', side: 'ally', max: 1 }], post: { removeTopDebuff: true, healIfRemoved: { amount: 2 } }, animationMs: 1200 },
    animation: 'Healing_2x2_4frames',
    animationPlacement: 'inplace'
  },
  clericHeal: {
    id: 'clericHeal', name: 'Heal',
    description: 'Targets the two allies with the lowest Health, with a Heal Power of 5 (+spellPower).',
    spec: { targets: [{ type: 'lowestHealth', side: 'ally', max: 2 }], formula: { type: 'healPower', value: 5 }, animationMs: 1200 },
    animation: 'Healing_2x2_4frames', animationPlacement: 'inplace'
  },
  // Dragonling spells (each heals the caster for 2 and applies Dragon Year to self)
  // Note: Dragonling secondary heals are flat (ignoreSpellPower: true) unlike other secondaryHeals
  tailWhip: {
    id: 'tailWhip', name: 'Tail Whip',
    description: 'Targets the frontmost enemy row that has at least one Hero, dealing 2 Attack Power. Heals caster for 2 and applies Dragon Year (+2 Spell Power, +1 Armor).',
    spec: { targets: [{ type: 'frontmostRowWithHero', side: 'enemy' }, { type: 'self' }], formula: { type: 'attackPower', value: 2 }, post: { secondaryHeal: { amount: 2, side: 'ally', target: 'self', ignoreSpellPower: true }, applyEffectToSelf: { effects: ['DragonYear'] } }, animationMs: 1200 },
    animation: 'Tail Whip_2x2_4frames', animationPlacement: 'travel', animationSecondary: 'Healing_2x2_4frames'
  },
  dragonsBreath: {
    id: 'dragonsBreath', name: "Dragon's Breath",
    description: 'Column attack dealing 1 Attack Power. Heals caster for 2 and applies Dragon Year (+2 Spell Power, +1 Armor).',
    spec: { targets: [{ type: 'column', side: 'enemy' }, { type: 'self' }], formula: { type: 'attackPower', value: 1 }, post: { secondaryHeal: { amount: 2, side: 'ally', target: 'self', ignoreSpellPower: true }, applyEffectToSelf: { effects: ['DragonYear'] } }, animationMs: 1200 },
    animation: 'Dragon Breath_2x2_4frames', animationPlacement: 'travel', animationSecondary: 'Healing_2x2_4frames'
  },
  claw: {
    id: 'claw', name: 'Claw',
    description: 'Targets the enemy with the highest Health, dealing 3 Attack Power. Heals caster for 2 and applies Dragon Year (+2 Spell Power, +1 Armor).',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }, { type: 'self' }], formula: { type: 'attackPower', value: 3 }, post: { secondaryHeal: { amount: 2, side: 'ally', target: 'self', ignoreSpellPower: true }, applyEffectToSelf: { effects: ['DragonYear'] } }, animationMs: 1200 },
    animation: 'Claw_2x2_4frames', animationPlacement: 'travel', animationSecondary: 'Healing_2x2_4frames'
  },

  // Ice Mage spells
  coneOfCold: {
    id: 'coneOfCold', name: 'Cone of Cold',
    description: 'Targets the enemy front and middle rows for 4 Attack Power. (50% chance to apply Slowed)',
    spec: { targets: [{ type: 'frontTwoRows', side: 'enemy' }], formula: { type: 'attackPower', value: 4 }, animationMs: 1200, post: { applyEffectWithChance: { effect: 'Slowed', chance: 0.5 } } },
    animation: 'Cone Of Cold_2x2_4frames', animationPlacement: 'inplace'
  },
  iceBolt: {
    id: 'iceBolt', name: 'Ice Bolt',
    description: 'Targets the enemy with the highest Health, dealing 7 Attack Power. (50% chance to apply Slowed)',
    spec: { targets: [{ type: 'highestHealth', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 7 }, animationMs: 1200, post: { applyEffectWithChance: { effect: 'Slowed', chance: 0.5 } } },
    animation: 'Ice Bolt_2x2_4frames',
    animationPlacement: 'travel'
  },
  blizzard: {
    id: 'blizzard', name: 'Blizzard',
    description: 'Targets the entire enemy board, dealing 5 Attack Power. (50% chance to apply Slowed to each target)',
    spec: { targets: [{ type: 'board', side: 'enemy' }], formula: { type: 'attackPower', value: 5 }, animationMs: 1200, post: { applyEffectWithChance: { effect: 'Slowed', chance: 0.5 } } },
    animation: 'Blizzard_2x2_4frames', animationPlacement: 'inplace'
  },

  // Axeman spells
  chop: {
    id: 'chop', name: 'Chop',
    description: 'Targets the frontmost enemy row that has at least 1 Hero, dealing 3 Attack Power.',
    spec: { targets: [{ type: 'frontmostRowWithHero', side: 'enemy' }], formula: { type: 'attackPower', value: 3 }, animationMs: 1200 },
    animation: 'Chop_2x2_4frames', animationPlacement: 'inplace'
  },
  axeThrow: {
    id: 'axeThrow', name: 'Axe Throw',
    description: 'Projectile dealing 5 Attack Power.',
    spec: { targets: [{ type: 'projectile', side: 'enemy', max: 1 }], formula: { type: 'attackPower', value: 5 }, animationMs: 1200 },
    animation: 'Axe Throw_2x2_4frames', animationPlacement: 'travel'
  },
  sharpenAxe: {
    id: 'sharpenAxe', name: 'Sharpen Axe',
    description: 'Targets the caster and applies an effect: Power which increases Spell Power by 2.',
    spec: { targets: [{ type: 'self' }], effects: [EFFECTS.Power], animationMs: 1200 },
    animation: 'Elixir_2x2_4frames', animationPlacement: 'inplace'
  },

  // Executioner spells
  execute: {
    id: 'execute', name: 'Execute',
    description: 'Targets the enemy with the lowest Health, dealing Attack Power equal to 2 + the target\'s missing Health.',
    spec: { 
      targets: [{ type: 'lowestHealth', side: 'enemy', max: 1 }], 
      formula: { type: 'attackPower', value: 2, addTargetMissingHealth: true }, 
      animationMs: 1200 
    },
    animation: 'Excecute_2x2_4frames',
    animationPlacement: 'travel'
  },

  guillotine: {
    id: 'guillotine', name: 'Guillotine',
    description: 'Targets the enemy with the lowest Health, dealing 3 Attack Power and applying an effect: Bleed which deals 1 damage at the start of each Round.',
    spec: { 
      targets: [{ type: 'lowestHealth', side: 'enemy', max: 1 }], 
      formula: { type: 'attackPower', value: 3 }, 
      effects: [EFFECTS.Bleed], 
      animationMs: 1200 
    },
    animation: 'Guillotine',
    animationPlacement: 'travel'
  },

  shackle: {
    id: 'shackle', name: 'Shackle',
    description: 'Targets the enemy with the most positive effects and applies an effect: Shackle which prevents the effected Hero from being moved between Rounds or by any spells.',
    spec: { 
      targets: [{ type: 'mostBuffs', side: 'enemy', max: 1 }], 
      effects: [EFFECTS.Shackle], 
      animationMs: 1200 
    },
    animation: 'Shackle_2x2_4frames',
    animationPlacement: 'inplace'
  },

  // Fallen Angel spells
  darkPillar: {
    id: 'darkPillar', name: 'Dark Pillar',
    description: 'Column attack dealing 4 Attack Power and applying an effect: Curse which decreases Spell Power by 1.',
    spec: { 
      targets: [{ type: 'column', side: 'enemy' }], 
      formula: { type: 'attackPower', value: 4 }, 
      effects: [EFFECTS.Curse], 
      animationMs: 1200 
    },
    animation: 'Dark Pillar_2x2_4frames',
    animationPlacement: 'inplace'
  },

  retribution: {
    id: 'retribution', name: 'Retribution',
    description: 'Targets the caster and applies an effect: Retribution which deals 3 damage to any enemy who targets the effected Hero with a spell.',
    spec: { 
      targets: [{ type: 'self' }], 
      effects: [EFFECTS.Retribution], 
      animationMs: 1200 
    },
    animation: 'Elixir_2x2_4frames',
    animationPlacement: 'inplace'
  }
};

export function getSpellById(id) {
  return SPELLS[id] || null;
}

export default { SPELLS, getSpellById };
